config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # We want to see multiple products
  resources :products do
    resources :order_items
  end

  # We want our users to order multiple times
  resources :orders

  # We only want the user to see ONLY one cart!
  resource :cart

  get "info", to: "pages#info"

  root "pages#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items

  def total_quantity
    @count = 0

    order_items.all.each do |item|
      @count = @count + item.quantity
    end

    @count # This is what we return at the end of the function
  end

  def total_price
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price * item.quantity
    end

    @total
  end

  def total_price_in_dollars
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price_in_dollars * item.quantity
    end

    @total
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :address_1, presence: true
  validates :city, presence: true
  validates :country, presence: true

  # This let us reaching out in active admin the order items inside the order
  accepts_nested_attributes_for :order_items

  # We want to add the cart items to the order
  def add_items_from_cart(cart)
    cart.order_items.all.each do |item|
      #self refers to the individual order
      self.order_items.new(product: item.product, quantity: item.quantity)
    end
  end

  # Saving the order and charging in Stripe
  def save_and_charge
    # Check our data if it's valid
    if self.valid?
    #If if it's valid, charge
      Stripe::Charge.create(amount: self.total_price, currency: "USD", source: self.stripe_token, description: "Order for #{self.email}")

      self.save

    else
      false # Not valid, show error
    end

  rescue Stripe::CardError => e
        # This is coming from stripe documentation
        @message = e.json_body[:error][:message]

        # Beside validation errors, we can create our own errors
        self.errors.add(:stripe_token, @message)

        # Return false to our controller
        false

  end

  def total_price
    @total = 0

    order_items.each do |item|
      @total = @total + item.product.price * item.quantity
    end

    @total
  end

  def total_price_in_dollars
    @total = 0

    order_items.all.each do |item|
      @total = @total + item.product.price_in_dollars * item.quantity
    end

    @total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order, optional: true # Not every item will be an order
  belongs_to :cart, optional: true # Not every item will land in the cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true

  mount_uploader :image_1, ProductImageUploader
  mount_uploader :image_2, ProductImageUploader
  mount_uploader :image_3, ProductImageUploader
  mount_uploader :image_4, ProductImageUploader
  mount_uploader :image_5, ProductImageUploader

  def price_in_dollars
    price / 100 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart
  helper_method :current_cart

  def current_cart
    # if the customer has just landed on the site, give them a brand new cart
    # if they already have one, keep it
    # check session[:cart_id] -- cart_id just made up it can be basically anything

    if session[:cart_id].present?
      # They already have a cart
      @current_cart = Cart.find(session[:cart_id])
    else
      # We need to set up a new one
      @current_cart = Cart.create # This is equals with Cart.new.save
      session[:cart_id] = @current_cart.id
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    # Cart is already set up in application controller
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    #find the product
    # we are currently not in the product controller, so since the order_items are connected to the product, we can check the product_id
    @product = Product.find(params[:product_id])

    #what's the cart cart = @current_cart

    # Quantity comes from the form_data
    @quantity = form_params[:quantity]

    # Add the product to cart
    # Create equals with .new.save
    @current_cart.order_items.create(product: @product, quantity: @quantity)

    flash[:success] = "Thanks for adding to your cart!"

    redirect_to product_path(@product)
  end

  def update
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])

    # From the form_params we already got the change in quantity so based on that we can update it
    @order_item.update(form_params)

    flash[:success] = "Thanks for updating to your cart!"

    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find(params[:product_id])
    @order_item = OrderItem.find(params[:id])
    @order_item.delete

    flash[:success] = "Product removed from cart"

    redirect_to cart_path
  end

  def form_params
    params.require(:order_item).permit(:quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @order = Order.new

    # add_items_from_cart is defined on the order model
    # we place the order items into the order
    @order.add_items_from_cart(@current_cart)
  end

  def create
    @order = Order.new(form_params)
    @order.add_items_from_cart(@current_cart)

    if @order.save_and_charge
      # After order has been completed, we reset the cart for the customers
      reset_session

      flash[:success] = "Order completed!"

      # We want to send an order confirmation
      OrderMailer.receipt(@order).deliver_now

      # We redirect the customer to the thanks page
      redirect_to order_path(@order)
    else
      render "new"
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def form_params
    params.require(:order).permit(:first_name, :last_name, :email, :address_1, :address_2, :city, :country, :postal_code, :stripe_token)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @featured_products = Product.where(is_featured: true)
  end

  def info
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])

    # This only exists if we already added something to the basket
    @order_item = @current_cart.order_items.find_by(product: @product)

    # We need a backup if not
    if @order_item.nil?
      @order_item = @current_cart.order_items.new(product: @product, quantity: 1)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h2>Cart</h2>


<% if @current_cart.order_items.any? %>
  <table>
    <thead>
      <tr>
        <th>Item</th>
        <th>Price</th>
        <th>Qty</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @current_cart.order_items.each do |item| %>
        <tr>
          <td><%= image_tag item.product.image_1.thumb, width: "50" %><%= item.product.title %></td>
          <td><%= number_to_currency item.product.price_in_dollars %></td>
          <td><%= simple_form_for [item.product, item] do |f| %>
            <%= f.input :quantity, label: false %>
            <%= f.button :submit, "Add to cart" %>
          <% end %></td>
          <td>
            <%= link_to "Remove", product_order_item_path(item.product, item), method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>
    Total: <%= number_to_currency @current_cart.total_price_in_dollars %>
  </p>

  <p>
    <%= link_to "Continue to checkout", new_order_path %>
  </p>

  <% else %>
  <p class="empty">
    There are no items in your cart. :(
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotherpin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Another Pin Co", root_path %></h1>

      <nav>
        <%= link_to "Shop", products_path %>
        <%= link_to "Info", info_path %>
        <%= link_to cart_path do %>
          Cart (<%= @current_cart.total_quantity %>)
        <% end %>
      </nav>
    </header>

    <% if flash[:success].present? %>
      <div class="flash-success">
        <%= flash[:success] %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer>
      Copyright 2017
    </footer>

  </body>
</html>

app/views/orders/new.html.erb
<h1>Checkout</h1>
<p>
  Total number of items: <%= @order.order_items.size %>
</p>

<%= simple_form_for @order do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>

  <%= f.input :email %>

  <%= f.input :country %>
  <%= f.input :address_1 %>
  <%= f.input :address_2 %>
  <%= f.input :city %>
  <%= f.input :postal_code %>

  <div class="card-details">
      <%= label_tag("Card Number") %>
      <div id="card-errors">
          <% @order.errors[:stripe_token].each do |message| %>
            <p><%= message %></p>
          <% end %>
      </div>

      <div id="cardNumber">

      </div>

       <div id="cardExpiry">
       </div>

      <div id="cardCVC">
      </div>
  </div>

  <%= f.button :submit, "Submit order" %>
<% end %>

<script>
  var stripe = Stripe("<%= Rails.application.secrets.stripe_public_key %>");
  var elements = stripe.elements();

  // Matching Stripe form styling to the rest
  var style = {
      fontFamily: '"Karla"',
      color: "#000",
      iconColor: "#000000",
      base: {
          "::placeholder": { color: "#ededeb"}
      }
    };

  // Create an instance of the card Element.
  var cardNumber = elements.create('cardNumber', {style: style});
  var cardExpiry = elements.create('cardExpiry', {style: style});
  var cardCVC = elements.create('cardCvc', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  cardNumber.mount('#cardNumber');
  cardExpiry.mount('#cardExpiry');
  cardCVC.mount('#cardCVC');

  $("form.new_order").on("submit", function(e) {
    e.preventDefault()

    stripe.createToken(card).then(function(result) {
       if (result.error) {
          $("#card-errors").html(result.error.message)
       } else {
         $("form.new_order").append("<input type=hidden name='order[stripe_token]' value=" + result.token.id + ">")
         $("form.new_order").get(0).submit()
       }
  })
})

</script>

app/views/orders/show.html.erb
<h1>Thanks for ordering!</h1>
<p>
  Your order has been received.
</p>

<p>
  <%= link_to "Back to home", root_path %>
</p>

app/views/pages/home.html.erb
<h1>Homepage!</h1>

<h2>Featured pins</h2>
<%= render partial: "products/product", collection: @featured_products %>
<%# Rendering the partial from the products folder %>
<%# Collection works as a loop %>

app/views/pages/info.html.erb
<h1>About Another Pin Co</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

app/views/products/_product.html.erb
<div class="product">
  <%= link_to product_path(product) do %>
    <%= image_tag product.image_1.medium %>
  <% end %>

  <h3><%= link_to product.title, product_path(product) %></h3>

  <p>
    <%= number_to_currency product.price_in_dollars %>
    <%# price in dollars method defined on the product model so we can use directly in the view %>
    <%# number_to_currency is a helper method built-in rails %>

  </p>
</div>

app/views/products/index.html.erb
<h2>2017 Collection</h2>

<%= render partial: "product", collection: @products %>

app/views/products/show.html.erb
<h2><%= @product.title %></h2>

<%= simple_format @product.description %>

<%= simple_form_for [@product, @order_item] do |f| %>
  <%= f.input :quantity %>
  <%= f.button :submit, "Add to cart" %>
<% end %>

<p>
  <%= link_to "Back to all products", products_path %>
</p>